const semirings = ConstStore{Abstract_GrB_Semiring}()
const monoids = ConstStore{Abstract_GrB_Monoid}()
const binaryops = ConstStore{Abstract_GrB_BinaryOp}()
const unaryops = ConstStore{Abstract_GrB_UnaryOp}()
const selectops = ConstStore{Abstract_GrB_SelectOp}()
